### ISSUE TITLE
✅Feature: 도서 분석 화면 추가

### ISSUE THREAD

**Issue by rlarjsdn3** [rlarjsdn3/bookybooky-ios#6]
## Description
도서 분석 화면을 추가합니다. 도서 분석 화면에서는 분류 별 총 읽은 페이지(원형 차트)와 일일 총 읽은 페이지(막대 그래프) 차트를 제공해야 합니다. 그리고 연속 독서일, 주 독서 분야 등 여러 하이라이트 또한 제공합니다. 이 기능은 iOS 17에 대응하는 기능입니다.

## To-Do
- [x] '분류별 총 읽은 페이지 막대 차트' 구현
- [x] '일일 총 읽은 페이지 원형 차트' 구현
- [x] 하이라이트 보기 구현

## Etc
이 기능은 iOS 17에 대응되는 기능으로, iOS 17+에서만 사용 가능하도록 최소 사양(Minimum Deployment)을 변경해야 합니다.
